import { useState } from 'react';
import { motion } from 'framer-motion';
import { states, State } from '@/data/states';
import StateTooltip from './StateTooltip';
import StateModal from './StateModal';

export default function IndiaMap() {
  const [hoveredState, setHoveredState] = useState<State | null>(null);
  const [tooltipPosition, setTooltipPosition] = useState({ x: 0, y: 0 });
  const [selectedState, setSelectedState] = useState<State | null>(null);

  const handleMouseEnter = (event: React.MouseEvent<SVGPathElement>, state: State) => {
    setHoveredState(state);
    setTooltipPosition({ x: event.clientX, y: event.clientY });
  };

  const handleMouseLeave = () => {
    setHoveredState(null);
  };

  const handleClick = (state: State) => {
    setSelectedState(state);
  };

  const handleCloseModal = () => {
    setSelectedState(null);
  };

  // Define the SVG viewBox based on the placeholder paths.
  // These values are arbitrary for the placeholder shapes.
  // For a real map, these would be derived from the actual SVG data.
  const viewBox = "0 0 600 400";

  return (
    <div className="relative w-full overflow-hidden flex justify-center items-center py-8">
      <motion.svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox={viewBox}
        className="w-full h-auto max-w-4xl" // Max-width for scaling
        initial={{ opacity: 0, scale: 0.8 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.8, ease: 'easeOut' }}
      >
        {states.map((state) => (
          <motion.path
            key={state.id}
            d={state.svgPath}
            className="cursor-pointer transition-all duration-300 ease-in-out"
            // Using CSS variables generated by Tailwind plugin for dynamic fill colors
            fill={
              selectedState?.id === state.id
                ? 'var(--tw-accent)'
                : hoveredState?.id === state.id
                ? 'var(--tw-primary)'
                : 'var(--tw-neutral-400)'
            }
            stroke="var(--tw-neutral-600)" // Border color
            strokeWidth="1"
            onMouseEnter={(e) => handleMouseEnter(e, state)}
            onMouseMove={(e) => setTooltipPosition({ x: e.clientX, y: e.clientY })} // Update tooltip position
            onMouseLeave={handleMouseLeave}
            onClick={() => handleClick(state)}
            whileHover={{ scale: 1.01 }} // Slight scale on hover
            whileTap={{ scale: 0.99 }} // Slight shrink on click
          />
        ))}
      </motion.svg>

      {hoveredState && (
        <StateTooltip
          name={hoveredState.name}
          capital={hoveredState.capital}
          x={tooltipPosition.x}
          y={tooltipPosition.y}
          isVisible={true}
        />
      )}

      <StateModal state={selectedState} onClose={handleCloseModal} />
    </div>
  );
}